apiVersion: v1
kind: Service
metadata:
  name: playground-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: playground
  type: NodePort
status:
  loadBalancer: {}